src/Entity/Property.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\PropertyRepository")
 */
class Property
{

    const HEAT = [
        0 => 'Electrique',
        1 => 'Gaz'
    ];

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="integer")
     * @Assert\Range(min=10, max=400)
     */
    private $surface;

    /**
     * @ORM\Column(type="integer")
     */
    private $rooms;

    /**
     * @ORM\Column(type="integer")
     */
    private $bedrooms;

    /**
     * @ORM\Column(type="integer")
     */
    private $floor;

    /**
     * @ORM\Column(type="integer")
     */
    private $price;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $city;

    /**
     * @ORM\Column(type="boolean", options={"default": false})
     */
    private $sold;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\Column(type="integer")
     */
    private $heat;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getSurface(): ?int
    {
        return $this->surface;
    }

    public function setSurface(int $surface): self
    {
        $this->surface = $surface;

        return $this;
    }

    public function getRooms(): ?int
    {
        return $this->rooms;
    }

    public function setRooms(int $rooms): self
    {
        $this->rooms = $rooms;

        return $this;
    }

    public function getBedrooms(): ?int
    {
        return $this->bedrooms;
    }

    public function setBedrooms(int $bedrooms): self
    {
        $this->bedrooms = $bedrooms;

        return $this;
    }

    public function getFloor(): ?int
    {
        return $this->floor;
    }

    public function setFloor(int $floor): self
    {
        $this->floor = $floor;

        return $this;
    }

    public function getPrice(): ?int
    {
        return $this->price;
    }

    public function getFormatedPrice(): ?string
    {
        return number_format($this->price, 0, '', ' ');
    }

    public function setPrice(int $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getSold(): ?bool
    {
        return $this->sold;
    }

    public function setSold(bool $sold): self
    {
        $this->sold = $sold;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getHeat(): ?int
    {
        return $this->heat;
    }

    public function getFormatedHeat(): ?string
    {
        return $this::HEAT[$this->heat];
    }

    public function setHeat(int $heat): self
    {
        $this->heat = $heat;

        return $this;
    }
}

src/Form/PropertyType.php
<?php

namespace App\Form;

use App\Entity\Property;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PropertyType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title')
            ->add('description')
            ->add('surface')
            ->add('rooms')
            ->add('bedrooms')
            ->add('floor')
            ->add('price')
            ->add('city')
            ->add('sold')
            ->add('heat')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Property::class,
        ]);
    }
}

src/Controller/PropertyController.php
<?php

namespace App\Controller;

use App\Repository\PropertyRepository;
use Doctrine\Common\Persistence\ObjectManager;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class PropertyController extends AbstractController
{

    public function __construct(PropertyRepository $repository, ObjectManager $em)
    {
        $this->repository = $repository;
    }

    /**
     * @Route("/properties", name="property.index")
     */
    public function index()
    {
        $properties = $this->repository->findAll();
        
        return $this->render('property/index.html.twig', [
            'controller_name' => 'PropertyController',
            'current_menu' => 'properties',
            'properties' => $properties
        ]);
    }

    /**
     * @Route("/property/{id}", name="property.show")
     */
    public function show($id) 
    {
        $property = $this->repository->find($id);
        
        return $this->render('property/show.html.twig', [
            'controller_name' => 'PropertyController',
            
            'property' => $property
        ]);
    }

}

templates/property/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello PropertyController!{% endblock %}

{% block body %}
<div class="jumbotron text-center">
<h1>Sisi</h1>
<p>Lorem ipsum dolor, sit amet jb jb pisicing elit. Sed quos asperiores nihil, nisi quasi illum deleniti delectus. Iusto impedit excepturi magnam? Fuga corrupti odit voluptatum officiis? Impedit labore nulla nam?</lorel></p>
</div>

<div class="container">
<div class="row flex">
    {% for property in properties %}
        <div class="col-3">
        <div class="card">
        <div class="card-body">
        <h5 class="card-title">
        <a href="{{ path('property.show', {'id': property.id}) }}">{{ property.title }}</a>
        ({{ property.rooms }} rooms)
        </h5>
        <p class="card-text">{{ property.city }}</p>
        <div class="text-primary">{{ property.formatedPrice }} €</div>
        </div>
        </div>
        </div>
    {% endfor %}
</div>
</div>
{% endblock %}

templates/property/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Property view{% endblock %}

{% block body %}
<div class="jumbotron text-center">
<h1>Agence Immo</h1>
<p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Sed quos asperiores nihil, nisi quasi illum deleniti delectus. Iusto impedit excepturi magnam? Fuga corrupti odit voluptatum officiis? Impedit labore nulla nam?</lorel></p>
</div>

<div class="container">
<div class="row flex">
    
        <div class="col-8">
        
        <h1 class="card-title">       {{ property.title }}        </h1>
        <h2>{{ property.rooms }} pièces - {{ property.surface }} m²</h2>
        <h3>{{ property.formatedHeat }}</h3>

        <p class="card-text">{{ property.city }}</p>


        <div class="text-primary">{{ property.formatedPrice }} €</div>
        <a href="#" class="btn btn-primary">Nous Contacter</a>
        </div>
    
</div>
</div>
{% endblock %}